### ISSUE TITLE
payment

### ISSUE THREAD

**Issue by AnneeSam** [NowSquare/Mobile-Platform#2]
payment mail problem

**Comment by richardwing** [comment]
I think that may be because the return url used for return from canceling and possibly the ipn notification url is not sent to paypal correctly I believe it may be missing a colon from the url. I have an unrelated issue with canceling at paypal where the return url used to take me back is missing a colon and formatting like so https//

**Comment by richardwing** [comment]
Did you resolve this? Is that why you closed this?
